88 delete/donors/id
GSG-G11/Indonate pull request #106
Opened 2022-05-09 00:18 UTC by DeenaAlghazali

2022-05-09 00:34 UTC, HaniOlwan approved these changes

2022-05-09 08:05 UTC, Raghad-Mezied requested changes

2022-05-09 08:05 UTC, Raghad-Mezied commented on server/controllers/admin/donors/deleteDonorById.ts
> +    res.status(200).json({ message: 'Deleted successfully' });
As 200 is the default so you can don't send it.

2022-05-09 08:05 UTC, Raghad-Mezied commented on server/routes/adminDonor.ts
> +adminDonorRouter.route('/donor/:id').delete(deleteDonorById);
Again is it allowed for anyone to delete a doner?

2022-05-09 17:03 UTC, Raghad-Mezied requested changes

2022-05-09 17:03 UTC, Raghad-Mezied commented on server/controllers/admin/donors/deleteDonorById.ts
> +    if (!deletedDonor) throw new CustomError('ID does not exist', 400);
This message will be shown to the user, so add a more user-friendly message.

2022-05-09 17:03 UTC, Raghad-Mezied commented on server/tests/route.test.ts
> +  });
Test the case with an unauthorized user

2022-05-09 20:53 UTC, Raghad-Mezied approved these changes

2022-05-09 20:59 UTC, Raghad-Mezied approved these changes

2022-05-09 21:58 UTC, HaniOlwan approved these changes

2022-05-09 22:03 UTC, Mohammed-Hamada requested changes

2022-05-09 22:03 UTC, Mohammed-Hamada commented on server/controllers/admin/donors/deleteDonorById.ts
> +    if (!deletedDonor) throw new CustomError('The donor you are trying to delete does not exist', 400);
`doesn't`

2022-05-09 22:03 UTC, Mohammed-Hamada commented on server/controllers/admin/donors/deleteDonorById.ts
> +    res.json({ message: 'Deleted successfully' });
`Donor deleted successfully`

2022-05-09 22:03 UTC, Mohammed-Hamada commented on server/controllers/admin/donors/deleteDonorById.ts
> +    if (error.name === 'ValidationError') next(new CustomError(error.details[0].message, 400));
just you want to send `error.message`, that equals `error.details[0].message`

2022-05-09 22:47 UTC, farah2003 approved these changes

2022-05-10 15:22 UTC, Mohammed-Hamada approved these changes

2022-05-10 16:03 UTC, merged