Admin Get All families
GSG-G11/Indonate pull request #113
Opened 2022-05-10 19:56 UTC by HaniOlwan

- route : /api/admin/families/?page 
- validate page must be a number 
- add limit and offset to query 
- dublicating false to fix sequlize bug 
- get donations for a single family by setting the relation between family model and capon model , sum the donations for that family and group them by family id 
- sort data in desend order using id and name 
- send the response data with a success message or else throw error for validation error or unauthed user admin

2022-05-12 10:13 UTC, Mohammed-Hamada approved these changes

2022-05-12 10:15 UTC, farah2003 approved these changes

2022-05-12 10:40 UTC, Raghad-Mezied requested changes

2022-05-12 10:40 UTC, Raghad-Mezied commented on server/database/models/capon.ts
> +  },
Remove the id

2022-05-13 07:30 UTC, Raghad-Mezied approved these changes

2022-05-13 13:32 UTC, merged