Admin Delete Campaign
GSG-G11/Indonate pull request #117
Opened 2022-05-11 00:59 UTC by HaniOlwan

2022-05-11 06:23 UTC, Raghad-Mezied requested changes

2022-05-11 06:23 UTC, Raghad-Mezied commented on server/controllers/admin/campaign/deleteCampaign.ts
> +    next();
Why this next ?

2022-05-12 11:47 UTC, farah2003 approved these changes

2022-05-13 00:29 UTC, DeenaAlghazali approved these changes

2022-05-13 20:23 UTC, Mohammed-Hamada approved these changes

2022-05-13 20:25 UTC, Raghad-Mezied approved these changes

2022-05-14 10:54 UTC, merged