Admin Get Family Campaigns
GSG-G11/Indonate pull request #121
Opened 2022-05-11 12:06 UTC by HaniOlwan

Relates #120

2022-05-12 11:50 UTC, farah2003 approved these changes

2022-05-12 18:22 UTC, Mohammed-Hamada requested changes

2022-05-13 00:30 UTC, DeenaAlghazali approved these changes

2022-05-13 07:34 UTC, Raghad-Mezied requested changes

2022-05-13 07:34 UTC, Raghad-Mezied commented on server/controllers/admin/families/getCampaigns.ts
> +      throw new CustomError("Family doesn't exist", 400);
If there is no family then nothing wrong with the request, there is just no data

2022-05-13 20:24 UTC, Mohammed-Hamada approved these changes

2022-05-13 20:38 UTC, Raghad-Mezied approved these changes

2022-05-13 21:02 UTC, merged