102 get donors route
GSG-G11/Indonate pull request #122
Opened 2022-05-11 15:46 UTC by farah2003

relates #102 
close #102

2022-05-12 11:56 UTC, Mohammed-Hamada approved these changes

2022-05-13 00:31 UTC, DeenaAlghazali approved these changes

2022-05-13 22:21 UTC, HaniOlwan commented on server/controllers/admin/donors/getDonors.ts
> +const getDonors = async (req:Request, res:Response, next:NextFunction) => {
change the name to getDonorsForCampaign just to be more clear

2022-05-13 22:21 UTC, HaniOlwan commented on server/controllers/admin/donors/getDonors.ts
> +const getDonors = async (req:Request, res:Response, next:NextFunction) => {
change the name to getDonorsForCampaign just to be more clear

2022-05-13 22:22 UTC, HaniOlwan commented on server/controllers/admin/donors/getDonors.ts
> +    await donorsQuerySchema.validateAsync(req.query);
short the two lines for 
const { page = 1, limit = 6 } = donorsQuerySchema.validateAsync(req.query);

2022-05-13 22:22 UTC, HaniOlwan commented on server/controllers/admin/donors/getDonors.ts
> +    await donorsQuerySchema.validateAsync(req.query);
short the two lines for 
const { page = 1, limit = 6 } = donorsQuerySchema.validateAsync(req.query);

2022-05-13 22:23 UTC, HaniOlwan approved these changes

2022-05-14 08:46 UTC, Raghad-Mezied requested changes

2022-05-14 08:46 UTC, Raghad-Mezied commented on server/controllers/admin/donors/getDonors.ts
> +import { donorsQuerySchema } from '../../../utils/validation';
Import them in one line from the utils

2022-05-14 08:46 UTC, Raghad-Mezied commented on server/database/fakeData/buildFakeData.ts
> +  await Promise.all(campaigns.map((campaign: any) => Campaign.create(campaign)));
Move this to the first Promis

2022-05-14 19:18 UTC, Raghad-Mezied approved these changes

2022-05-14 20:39 UTC, merged