127 patch admin campaign
GSG-G11/Indonate pull request #128
Opened 2022-05-11 23:01 UTC by farah2003

2022-05-13 00:35 UTC, DeenaAlghazali approved these changes

2022-05-13 22:13 UTC, HaniOlwan commented on server/controllers/donations/addDonation.ts
> +      console.log(error);
remove log

2022-05-14 08:23 UTC, Raghad-Mezied requested changes

2022-05-14 08:23 UTC, Raghad-Mezied commented on server/controllers/admin/campaign/updateCampaign.ts
> +import { campaignSchema } from '../../../utils/validation';
Import in one line

2022-05-14 08:23 UTC, Raghad-Mezied commented on server/utils/validation/campaignSchema.ts
> +  is_available: Joi.boolean().required(),
Update the is_available will be in another route right?

2022-05-14 19:33 UTC, Raghad-Mezied approved these changes

2022-05-14 19:43 UTC, HaniOlwan approved these changes

2022-05-15 17:58 UTC, merged