Admin Patch Doners
GSG-G11/Indonate pull request #130
Opened 2022-05-12 17:03 UTC by HaniOlwan

2022-05-12 18:52 UTC, Mohammed-Hamada requested changes

2022-05-12 18:52 UTC, Mohammed-Hamada commented on server/routes/adminDonor.ts
> +adminDonorRouter.route('/donors/:id').patch(authUser, authAdmin, updateDonorById);
try to refactor these two routes

2022-05-13 20:26 UTC, Mohammed-Hamada approved these changes

2022-05-13 21:04 UTC, DeenaAlghazali approved these changes

2022-05-14 08:24 UTC, Raghad-Mezied requested changes

2022-05-14 08:24 UTC, Raghad-Mezied commented on server/controllers/admin/donors/updateDonorById.ts
> +import { donorSchema } from '../../../utils/validation';
Import from the utils

2022-05-14 08:37 UTC, Mohammed-Hamada approved these changes

2022-05-14 19:20 UTC, farah2003 approved these changes

2022-05-14 19:25 UTC, Raghad-Mezied approved these changes

2022-05-15 12:49 UTC, merged