124 post admin families campaigns
GSG-G11/Indonate pull request #131
Opened 2022-05-12 22:48 UTC by farah2003

relates #124

2022-05-15 16:00 UTC, DeenaAlghazali approved these changes

2022-05-15 16:05 UTC, Mohammed-Hamada approved these changes

2022-05-16 19:43 UTC, HaniOlwan approved these changes

2022-05-17 11:19 UTC, Raghad-Mezied requested changes

2022-05-17 11:19 UTC, Raghad-Mezied commented on server/controllers/admin/campaign/postFamiliesForCampaign.ts
> +    });
Cant you just get the campaign and check the availability once?

2022-05-17 11:19 UTC, Raghad-Mezied commented on server/controllers/admin/campaign/postFamiliesForCampaign.ts
> +
Why do you add the families? they already exist.

2022-05-17 13:43 UTC, Raghad-Mezied approved these changes

2022-05-17 13:49 UTC, merged