16 setup database
GSG-G11/Indonate pull request #18
Opened 2022-04-21 16:01 UTC by DeenaAlghazali

2022-04-21 17:38 UTC, Mohammed-Hamada requested changes
Folder name should be `models` not `modules`

2022-04-21 17:38 UTC, Mohammed-Hamada commented on server/database/config/connection.ts
> +sequelize
Use `async` `await` instead of  `.then()`
try to see this [article](https://github.com/FarahZaqout/intro-async-await)

2022-04-21 17:38 UTC, Mohammed-Hamada commented on server/database/config/connection.ts
> +User.create({ first_name: 'donor' }).then((value: any) => console.log(value));
Also here, `async` `await`
and try to remove `console.log()`

2022-04-21 17:38 UTC, Mohammed-Hamada commented on server/database/modules/campaign.ts
> +const campaign = sequelize.define('campaigns', {
best `sequelize` naming convention that model name should be `Upper Case`
![image](https://user-images.githubusercontent.com/71943250/164517836-92494d71-98ad-40ec-aa40-91748ccb3db1.png)

2022-04-21 17:38 UTC, Mohammed-Hamada commented on server/database/modules/capon.ts
> +const capon = sequelize.define('donations', {
`Donation` is more understandable than `capon`

2022-04-21 17:38 UTC, Mohammed-Hamada commented on server/database/config/connection.ts
> +const User = sequelize.define('users', {
Is there need to this model?

2022-04-21 18:03 UTC, Raghad-Mezied requested changes

2022-04-21 18:03 UTC, Raghad-Mezied commented on server/database/modules/index.ts
> +};
You need to rename all your models to start with a capital letter. Also, rename this folder to models instead of modules.

2022-04-21 18:18 UTC, HaniOlwan reviewed
email: {
    type: DataTypes.STRING,
    allowNull: false,
    unique: true  <==  In Contacts model email should not be unique
      user can submit another issue },

2022-04-21 18:50 UTC, Raghad-Mezied requested changes

2022-04-21 18:50 UTC, Raghad-Mezied commented on server/database/modules/campaign.ts
> +    allowNull: true,
why this is allowed to be null?

2022-04-21 18:50 UTC, Raghad-Mezied commented on server/database/modules/campaign.ts
> +
Name it as it is boolean, I mean is_available or something like this

2022-04-21 18:50 UTC, Raghad-Mezied commented on server/database/modules/contact.ts
> +    unique: true,
Do we really need the email to be unique?

2022-04-21 18:50 UTC, Raghad-Mezied commented on server/database/modules/donor.ts
> +  },
You need to add that it is not allowed to be null, right?
The same for the family model.

2022-04-21 21:28 UTC, farah2003 approved these changes

2022-04-21 21:29 UTC, Mohammed-Hamada approved these changes
Good Job, I expect more and more in next issues 👏

2022-04-22 02:24 UTC, HaniOlwan approved these changes

2022-04-22 11:21 UTC, Raghad-Mezied approved these changes

2022-04-22 11:25 UTC, merged