23 fake data
GSG-G11/Indonate pull request #24
Opened 2022-04-22 13:35 UTC by DeenaAlghazali

You can use `npm run db:fake` to create fake data

2022-04-22 14:41 UTC, Raghad-Mezied requested changes

2022-04-22 14:41 UTC, Raghad-Mezied commented on server/database/fakeData/categoryData.ts
> +  },
these are not a category, change them so they don't lead to a misunderstanding. and you can just name it `categories` without all.

2022-04-22 14:41 UTC, Raghad-Mezied commented on server/database/fakeData/campaignsData.ts
> +    is_available: true,
What about the category?

2022-04-22 14:41 UTC, Raghad-Mezied commented on server/database/fakeData/categoryData.ts
> +  },
I think there is an icon too.

2022-04-22 14:44 UTC, Raghad-Mezied requested changes

2022-04-22 14:44 UTC, Raghad-Mezied commented on server/database/fakeData/index.ts
> +caponData();
Why not create just one function to add all your fake data.

2022-04-22 14:44 UTC, Raghad-Mezied commented on server/database/fakeData/contactData.ts
> +  },
I prefer to move all fake data to a separated `json` file.

2022-04-22 14:46 UTC, Raghad-Mezied commented
Good job Deena, great commits and description.

2022-04-23 02:46 UTC, Raghad-Mezied requested changes

2022-04-23 02:46 UTC, Raghad-Mezied commented on server/database/fakeData/data.json
> +    {
This is better than before, but I need you to create a folder for your fake data and add `json` file to each table separately.

2022-04-23 02:46 UTC, Raghad-Mezied commented on package.json
> +    "db:fake": "NODE_ENV=dev ts-node server/database/fakeData/index.ts --resolveJsonModule"
You can add a short explanation in the description of this script and for `--resolveJsonModule`.

2022-04-23 02:46 UTC, Raghad-Mezied commented on server/database/fakeData/index.ts
> +// eslint-disable-next-line import/extensions
Do you still need this after editing the eslint rules ?

2022-04-23 02:46 UTC, Raghad-Mezied commented on server/database/fakeData/index.ts
> +} = data;
If you are declaring several variables then don't put them in one long line like this, rewrite them like this
```js
const {
campaigns, 
capons, 
categories, 
messages, 
donations, 
donors, 
families,
} = data;
```

2022-04-23 02:46 UTC, Raghad-Mezied commented on server/database/fakeData/index.ts
> +  if (process.env.NODE_ENV === 'dev') {
What if the env is not a development? You still need to build your fake data. The difference is when you are in a development you run your script to build the data but the script just reads this file which we define a function but we don't use it so we need to invoke it, whereas in the test env we invoke this function in our test files so we don't need to invoke it here again, that why you need to move this condition to the line where you invoke the function.

2022-04-23 02:46 UTC, Raghad-Mezied commented on server/database/fakeData/index.ts
> +const buildData = async () => {
I think it's better to rename the file name to something that shows that we are building the fake data here.

2022-04-23 04:28 UTC, Raghad-Mezied approved these changes

2022-04-23 09:33 UTC, Mohammed-Hamada requested changes

2022-04-23 13:57 UTC, Mohammed-Hamada approved these changes
Great work deena, you made big effort, Thanks a lot..

2022-04-23 14:02 UTC, farah2003 approved these changes

2022-04-23 14:04 UTC, HaniOlwan approved these changes

2022-04-23 14:10 UTC, merged