create form Sgin up and its Items
GSG-G11/Indonate pull request #25
Opened 2022-04-22 16:06 UTC by farah2003

2022-04-23 12:54 UTC, Raghad-Mezied requested changes

2022-04-23 12:54 UTC, Raghad-Mezied commented on client/src/Component/signUp/index.jsx
> +} from 'antd';
add each one in a new line

2022-04-23 12:54 UTC, Raghad-Mezied commented on client/src/Component/signUp/index.jsx
> +function SignUp() {
Convert this to arrow function with function declaration

2022-04-23 12:54 UTC, Raghad-Mezied commented on client/src/Component/signUp/index.jsx
> +      const data = response.data.data[0];// user info object
Destructure the data here.

2022-04-23 12:54 UTC, Raghad-Mezied commented on client/src/feature/userReducer.js
> +});
Create a folder called redux, inside it put the app and the feature, inside the feature create another folder called user and put this file inside it, but rename it to userSlice.

2022-04-23 12:54 UTC, Raghad-Mezied commented on client/src/Component/signUp/index.jsx
> +                    return Promise.reject(new Error('The two passwords that you entered do not match!'));
Move this to separated function and then use it here

2022-04-23 12:54 UTC, Raghad-Mezied commented on client/src/Component/signUp/index.jsx
> +          }}
Move all the style to the css file.

2022-04-23 13:01 UTC, Raghad-Mezied requested changes

2022-04-23 13:01 UTC, Raghad-Mezied commented on client/src/Component/signUp/index.jsx
> +                onChange={(e) => setUserInfo({ ...userInfo, name: e.target.value })}
move this to a separated function and then use it

2022-04-23 15:13 UTC, Raghad-Mezied requested changes

2022-04-23 15:13 UTC, Raghad-Mezied commented on client/src/Component/signUp/index.jsx
> +              <Input.Password placeholder="Confirm password" />
Destructure the password, item and Tilte

2022-04-23 17:30 UTC, Raghad-Mezied requested changes

2022-04-23 17:30 UTC, Raghad-Mezied commented on client/.eslintrc.json
>  }
Add this rule for function decleration.
```js
        "react/function-component-definition": {
            "namedComponents": "function-declaration"
        }
```
And why there is two values for  `no-param-reassign`?

2022-04-23 17:30 UTC, Raghad-Mezied commented on client/src/Component/signUp/index.jsx
> +          style={{ color: '#fff' }}
Move the style to style files

2022-04-24 09:13 UTC, Mohammed-Hamada approved these changes

2022-04-25 14:16 UTC, Mohammed-Hamada approved these changes

2022-04-25 15:25 UTC, Raghad-Mezied approved these changes

2022-04-26 14:54 UTC, DeenaAlghazali approved these changes

2022-04-26 22:08 UTC, HaniOlwan approved these changes
Nice work

2022-04-26 22:54 UTC, merged