22 sign up
GSG-G11/Indonate pull request #29
Opened 2022-04-23 18:36 UTC by DeenaAlghazali

2022-04-23 18:59 UTC, Mohammed-Hamada requested changes

2022-04-23 18:59 UTC, Mohammed-Hamada commented on server/controllers/auth/signUp.ts
> +    await sign({ id: donor.id }, process.env.SECRET as string, (error:Error | null, token: string | undefined) => {
Here, I create function to sign token, so try to pull main in main and use it in your branch

2022-04-23 18:59 UTC, Mohammed-Hamada commented on server/utils/validation/signUpSchema.ts
> +  is_admin: Joi.boolean(),
There is no need to validate is_admin because here you just want to validate Sign Up form inputs.

2022-04-24 04:06 UTC, Raghad-Mezied requested changes

2022-04-24 04:06 UTC, Raghad-Mezied commented on server/controllers/auth/signUp.ts
> +        },
Do you need all this data to send as a response?

2022-04-24 04:06 UTC, Raghad-Mezied commented on server/controllers/auth/signUp.ts
> +    const donor: any = await Donor.create({
Edit all any types :satisfied:

2022-04-24 11:06 UTC, Mohammed-Hamada approved these changes

2022-04-24 12:16 UTC, Raghad-Mezied requested changes

2022-04-24 12:16 UTC, Raghad-Mezied commented on server/tests/route.test.ts
> +    expect(response.body.message).toBe('Sign up successfully');
you should check if your controller add a cookie or not

2022-04-24 12:16 UTC, Raghad-Mezied commented on server/controllers/auth/signUp.ts
> +  } catch (error: any) {
add type for the error

2022-04-24 12:16 UTC, Raghad-Mezied commented on server/controllers/auth/signUp.ts
> +      name, email, password: hashedPassword, phone, address,
Add each one in a new line, so you don't end up with a long line.

2022-04-24 12:16 UTC, Raghad-Mezied commented on server/controllers/auth/signUp.ts
> +    const check: any = await Donor.findOne({
edit the type

2022-04-24 18:45 UTC, Raghad-Mezied approved these changes

2022-04-24 20:22 UTC, farah2003 approved these changes

2022-04-25 00:29 UTC, HaniOlwan approved these changes

2022-04-25 01:29 UTC, merged