create checkAuth controllers
GSG-G11/Indonate pull request #31
Opened 2022-04-23 20:01 UTC by farah2003

2022-04-27 16:27 UTC, Raghad-Mezied commented on server/controllers/checkAuth.ts
> +};
You don't need to send the status code of 200 as it is the default and you already have the req.user object why you are creating a new one

2022-04-28 02:29 UTC, Raghad-Mezied requested changes

2022-04-28 02:29 UTC, Raghad-Mezied commented on server/tests/route.test.ts
> +    expect(response.body.message).toBe('Authorized user');
Test the data too, if it is as you expect.

2022-04-28 02:29 UTC, Raghad-Mezied commented on server/tests/route.test.ts
> +});
Here you should test the unAuthorized user, but this is the same as the first one

2022-04-28 02:29 UTC, Raghad-Mezied commented on server/controllers/auth/checkAuth.ts
> +  res.json({ data: req.user, message: 'Authorized user' });
Destructure the user and you don't need to send a message here.

2022-04-28 11:37 UTC, Raghad-Mezied requested changes

2022-04-28 11:37 UTC, Raghad-Mezied commented on server/tests/route.test.ts
> +});
Check the case where there is no `ACCESS_TOKEN` at all

2022-04-28 11:57 UTC, Mohammed-Hamada approved these changes
Good job farah 👏

2022-04-29 03:21 UTC, Raghad-Mezied approved these changes

2022-04-30 00:22 UTC, HaniOlwan approved these changes

2022-04-30 02:14 UTC, DeenaAlghazali approved these changes

2022-04-30 06:24 UTC, merged