38 get campaign
GSG-G11/Indonate pull request #40
Opened 2022-04-25 12:07 UTC by DeenaAlghazali

2022-04-25 14:48 UTC, Mohammed-Hamada requested changes

2022-04-25 14:48 UTC, Mohammed-Hamada commented on server/controllers/user/getCampaignById.ts
> +    res.status(200).json({ message: 'campaign information', data: campaignInfo });
`Success` because response successfully sent

2022-04-25 14:48 UTC, Mohammed-Hamada commented on server/tests/route.test.ts
> +    expect(response.body.data.target).toBe(data.target);
Format ☺

2022-04-25 15:48 UTC, Raghad-Mezied requested changes

2022-04-25 15:48 UTC, Raghad-Mezied commented on server/tests/route.test.ts
> +    expect(response.body.data.description).toBe(data.description);
Why not test them in just one line, I mean you have `response.body` and it should equal what you want.
And test the other cases.

2022-04-25 15:48 UTC, Raghad-Mezied commented on server/routes/userRoutes.ts
> +userRouter.route('/campaign/:id').get(getCampaignById);
Name it `compaignRouter`

2022-04-25 15:48 UTC, Raghad-Mezied commented on server/controllers/user/getCampaignById.ts
> +    const { id } = result;
Why not destructure the id immediately? instead of getting the result and then destructuring

2022-04-26 07:53 UTC, Raghad-Mezied approved these changes

2022-04-26 08:56 UTC, HaniOlwan approved these changes

2022-04-26 09:50 UTC, Mohammed-Hamada approved these changes
Great Work Deena

2022-04-26 09:55 UTC, farah2003 approved these changes

2022-04-26 10:12 UTC, merged