39 post reports
GSG-G11/Indonate pull request #41
Opened 2022-04-25 14:02 UTC by DeenaAlghazali

2022-04-25 14:38 UTC, Mohammed-Hamada requested changes
Awesome

2022-04-25 14:38 UTC, Mohammed-Hamada commented on server/controllers/user/reports.ts
> +    if (error.errors) next(new CustomedError('fail to create report', 400));
`Failed to create report`

2022-04-26 07:52 UTC, Raghad-Mezied approved these changes

2022-04-26 08:49 UTC, HaniOlwan approved these changes

2022-04-26 09:51 UTC, Mohammed-Hamada approved these changes

2022-04-26 09:54 UTC, farah2003 approved these changes

2022-04-26 09:55 UTC, merged