44 get campaign
GSG-G11/Indonate pull request #54
Opened 2022-04-26 17:41 UTC by farah2003

relates #44 

  ## Description:
  - [x] Get all campaign from database and filter it by category and send it to client
  - [x] Test all units

## Response:
  * Success (200):
```js
{
message: "Success",
data: {
campaines: []
}
```

2022-04-28 14:14 UTC, Mohammed-Hamada requested changes

2022-04-28 14:14 UTC, Mohammed-Hamada commented on server/controllers/compaignRouter/campaignes.ts
> +    if (e.details) {
Check error by its name

2022-04-29 04:04 UTC, Raghad-Mezied requested changes

2022-04-29 04:04 UTC, Raghad-Mezied commented on server/tests/route.test.ts
> +  });
Duplicated test

2022-04-29 04:04 UTC, Raghad-Mezied commented on server/tests/route.test.ts
> +  });
Test the response body too

2022-04-29 19:42 UTC, Raghad-Mezied approved these changes

2022-04-30 00:53 UTC, HaniOlwan approved these changes

2022-04-30 06:26 UTC, Mohammed-Hamada approved these changes

2022-04-30 12:02 UTC, DeenaAlghazali approved these changes

2022-04-30 13:09 UTC, merged