create donate form
GSG-G11/Indonate pull request #69
Opened 2022-04-28 18:58 UTC by DeenaAlghazali

2022-04-29 08:02 UTC, farah2003 requested changes

2022-04-29 10:26 UTC, Raghad-Mezied requested changes

2022-04-29 10:26 UTC, Raghad-Mezied commented on client/src/components/donateForm/index.jsx
> +        Donate
I think the visibility functionality will not be done here. Just do the modal and the logic of donation and Mohammed should connect it to the campaign page

2022-04-29 10:26 UTC, Raghad-Mezied commented on client/src/components/donateForm/index.jsx
> +      message.success(response.data.message);
Why this logic is not with the form component?

2022-04-29 10:26 UTC, Raghad-Mezied commented on client/src/components/donateForm/index.jsx
> +}) {
Why collection? name it something more descriptive

2022-04-30 01:04 UTC, farah2003 approved these changes

2022-04-30 01:10 UTC, HaniOlwan approved these changes

2022-04-30 02:07 UTC, Mohammed-Hamada approved these changes

2022-04-30 19:19 UTC, Raghad-Mezied approved these changes

2022-04-30 19:27 UTC, merged