fix structure of form an item should contain one child which is dateP…
GSG-G11/Indonate pull request #78
Opened 2022-05-01 02:40 UTC by DeenaAlghazali

…icker

2022-05-01 14:06 UTC, Raghad-Mezied approved these changes

2022-05-01 15:06 UTC, Raghad-Mezied requested changes
Since you don't need campaignId in the btn component then we don't need to pass it. The form component can access it throw the params.

2022-05-05 15:38 UTC, HaniOlwan approved these changes

2022-05-06 18:35 UTC, Raghad-Mezied approved these changes

2022-05-06 18:35 UTC, merged