Footer
GSG-G11/Indonate pull request #83
Opened 2022-05-05 22:54 UTC by HaniOlwan

Relates #64 
Closes #64 
![Screenshot from 2022-05-06 01-51-20](https://user-images.githubusercontent.com/49692805/167038912-94dd40e7-7ea0-413c-8513-bf99ed2a1fc7.png)

2022-05-06 18:29 UTC, Raghad-Mezied requested changes
Good Job Hani, I am not sure if the color of the logo is suitable for the background color.

2022-05-06 18:29 UTC, Raghad-Mezied commented on client/src/components/common/footer/index.jsx
> +import indonate from './logo.svg';
Move the logo to the assets folder

2022-05-08 11:53 UTC, Raghad-Mezied approved these changes

2022-05-08 12:57 UTC, farah2003 approved these changes

2022-05-08 12:57 UTC, DeenaAlghazali approved these changes

2022-05-08 12:59 UTC, Mohammed-Hamada approved these changes

2022-05-08 13:53 UTC, merged